name: Build Orangefox 12.1 Branch for Redmi 10X 5G (atom)
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Orangefox by ${{ github.actor }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set swap to 10G
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Prepare the build environment
      run: |
        sudo lsblk
        sudo umount /mnt
        sudo apt install parted -y
        sudo parted /dev/sdb --script rm 1
        lsblk /dev/sdb
        sudo parted /dev/sdb --script mkpart primary ext4 1MiB 100%
        sudo partprobe /dev/sdb
        sudo mkfs.ext4 /dev/sdb1
        lsblk -f /dev/sdb
        sudo mount /dev/sdb1 /mnt
        sudo chmod -R 777 /mnt
        export BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")
        cd /mnt
        sudo apt-get update
        sudo apt install git aria2 -y
        sudo DEBIAN_FRONTEND=noninteractive \
        apt install \
        adb autoconf automake axel bc bison build-essential \
        ccache clang cmake curl expat fastboot flex g++ \
        g++-multilib gawk gcc gcc-multilib git git-lfs gnupg gperf \
        htop imagemagick lib32ncurses5-dev lib32z1-dev libtinfo5 libc6-dev libcap-dev \
        libexpat1-dev libgmp-dev '^liblz4-.*' '^liblzma.*' libmpc-dev libmpfr-dev libncurses5-dev \
        libsdl1.2-dev libssl-dev libtool libxml2 libxml2-utils '^lzma.*' lzop \
        maven ncftp ncurses-dev patch patchelf pkg-config pngcrush \
        pngquant python2.7 python-all-dev re2c schedtool squashfs-tools subversion \
        texinfo unzip w3m xsltproc zip zlib1g-dev lzip \
        libxml-simple-perl libswitch-perl apt-utils \
        libncurses5 curl python-is-python3 -y
        sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
        sudo chmod a+rx /usr/local/bin/repo

    - name: Sync OrangeFox sources and minimal manifest
      run: |
        mkdir ~/mnt/OrangeFox_sync
        cd ~/OrangeFox_sync
        git clone https://gitlab.com/OrangeFox/sync.git
        cd ~/OrangeFox_sync/sync/
        ./orangefox_sync.sh --branch 12.1 --path /mnt/fox_12.1
    
    - name: Place device trees and kernel
      run: |
        cd /mnt/fox_12.1
        git clone https://github.com/mt6873-dev/orangefox_device_xiaomi_atom.git -b ofrp_12.1 device/xiaomi/atom

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: build-orangefox-atom
        max-size: 12G

    - name: Build Orangefox
      run: |
        cd /mnt/fox_12.1
        /bin/bash
        export ALLOW_MISSING_DEPENDENCIES=true
        export FOX_BUILD_DEVICE=atom
        export LC_ALL="C"
        export OF_PATCH_AVB20=1
        export OF_FORCE_PREBUILT_KERNEL=1
        source build/envsetup.sh
        lunch twrp_atom-eng && mka adbd recoveryimage
    
    - name: Check orangefox output files
      run: 
        ls -al /mnt/fox_12.1/out/target/product/
        echo
        ls -al /mnt/fox_12.1/out/target/product/atom/

    - name: Upload Orangefox
      uses: actions/upload-artifact@v4
      with:
        name: atom-${{ github.run_id }}
        path: |
          /mnt/fox_12.1/out/target/product/atom/*.zip
          /mnt/fox_12.1/out/target/product/atom/*.img

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          /mnt/fox_12.1/out/target/product/atom/*.img
          /mnt/fox_12.1/out/target/product/atom/*.zip
        name: atom-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Manifest: 12.1
          Device: atom
          Target: recovery
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
